name: Python File Writter CI

on:
  push:
    branches:
      - main
  pull-request:
    branches:
      - main
     

jobs:
  test:                      
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code            
        uses: actions/checkout@v4  #go to github market place --- All actions-- checkout ---uses

      - name: Set up Python  #go to github market place --- All actions-- python setup ---uses
        id: set-python
        uses: actions/setup-python@v5
        with:
         python-version: '3.13'

      - name: install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install pytest

      - name: Run tests
        run: pytest

 

     
         